name: Multiple steps failure pattern

on:
  workflow_dispatch:
    inputs:
      step-to-fail:
        description: "which step to fail"
        required: false
      
jobs:
  start:
    name: Call Action
    runs-on: ubuntu-latest
    outputs:
      errorStep: ${{ steps.action_id.outputs.error_step || steps.step-1.outputs.error_step || ''}}
      errorStepMessage: ${{ steps.action_id.outputs.error_step_message || steps.step-1.outputs.error_step_message || ''}}
    steps:
      - uses: actions/checkout@v4
      - name: step 1
        id: step-1
        run: |  
          echo "error_step=step-1" >> $GITHUB_OUTPUT
          echo "error_step_message=step-2" >> $GITHUB_OUTPUT
          if [[ '${{ github.event.inputs.step-to-fail }}' == '1' ]]; then
            exit 1
          fi
          
      - id: action_id
        uses: ./.github/actions/return-action
        with:
          test_property: "yes"
      - run: echo some output ${{ steps.action_id.outputs.return_info }}
  on_fail:
    name: Did fail?
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    needs: start
    steps:
      - run: |
            if [[ '${{ needs.start.result }}' == 'failure' ]]; then
              if [[ '${{ needs.start.outputs.errorStep }}' == 'return-action' ]]; then
                echo "Error step: ${{ needs.start.outputs.errorStep }}"
                echo "Error message: ${{ needs.start.outputs.errorStepMessage }}"
              fi
            fi
